# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]

#https://rojo.space/
rojo = "rojo-rbx/rojo@7.2.1"
# rojo = "rojo-rbx/rojo@6.2.0"
selene = "Kampfkarren/selene@0.23.1"
stylua = "JohnnyMorganz/Stylua@0.15.3"
