[package]
name = "me/default"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
# Knit = "sleitnick/knit@1.4.5"
# https://sleitnick.github.io/Knit/

Loader = "sleitnick/loader@2.0.0"
Net = "sleitnick/net@0.1.0"	

# Comm = "sleitnick/comm@0.2.3"
# Component = "sleitnick/component@2.4.5"
# EnumList = "sleitnick/enum-list@2.0.0"	
# Input = "sleitnick/input@1.3.3"	
# Log = "sleitnick/log@0.1.0"	
# Option = "sleitnick/option@1.0.3"
# PID = "sleitnick/pid@1.0.1"
# Ser = "sleitnick/ser@1.0.4"	
# Shake = "sleitnick/shake@0.1.5"	
# Signal = "sleitnick/signal@1.1.0"	
# Streamable = "sleitnick/streamable@1.2.3"	
# Symbol = "sleitnick/symbol@2.0.0"	
# TableUtil = "sleitnick/table-util@1.1.1"	
# TaskQueue = "sleitnick/task-queue@0.1.0"	
# Timer = "sleitnick/timer@1.1.1"	
# Trove = "sleitnick/trove@0.4.0"	
# WaitFor = "sleitnick/wait-for@0.2.1"
# https://sleitnick.github.io/RbxUtil/

Promise = "evaera/promise@4.0.0"
# https://eryn.io/roblox-lua-promise/

Matter = "evaera/matter@0.6.2"
# https://eryn.io/matter/

Janitor = "howmanysmall/janitor@1.14.1"
# https://howmanysmall.github.io/Janitor/

Fusion = "elttob/fusion@0.1.1-beta"
# https://elttob.github.io/Fusion/

# BitBuffer = "rstk/bitbuffer@1.0.0"
#https://rstk.github.io/BitBuffer/